# Generated by Django 4.0.1 on 2022-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_options_imagestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='passwordProtectedSteganographyImage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='steganographyImage',
            field=models.BooleanField(default=False),
        ),
    ]
